notifications:
  email: false

# cp26-cp26m  cp26-cp26mu  cp27-cp27m  cp27-cp27mu  cp33-cp33m  cp34-cp34m  cp35-cp35m
sudo: required

services:
  - docker

env:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp34-cp34m
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp34-cp34m PRE_CMD=linux32
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp35-cp35m PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - export PYVER=$PYVER
  - docker run -e "PYVER=$PYVER" --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
